MVCPractice/Models/ErrorViewModel.cs
namespace MVCPractice.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCPractice/Models/Student.cs
namespace MVCPractice.Models
{
    public class Student
    {
        public string FirstName { get; set; } = string.Empty;
        public string LastName { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;
    }
}

MVCPractice/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVCPractice.Models;

namespace MVCPractice.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCPractice/Controllers/StudentController.cs
using System.Security.Cryptography.X509Certificates;
using Microsoft.AspNetCore.Mvc;
using MVCPractice.Models;

namespace MVCPractice.Controllers
{
    public class StudentController : Controller
    {
        private static List<Student> students = new List<Student>();

        private static List<Student> loginStudent = new List<Student>();
        public IActionResult Index()
        {
            return View(students);
        }

        public IActionResult Register()
        {
            Student student = new Student();
            return View(student);
        }

        public IActionResult RegisterStudent(Student student)
        {
            students.Add(student);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Login()
        {
            Student student = new Student();
            return View(student);
        }

        public IActionResult LoginStudent(Student student)
        {
            loginStudent.Add(student);
            return RedirectToAction(nameof(Index));
        }
    }
}

MVCPractice/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCPractice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCPractice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCPractice.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Student" asp-action="Register">Register</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">List of student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVCPractice - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCPractice/Views/Student/Index.cshtml
@model List<MVCPractice.Models.Student>
<h3>List of all registerder student</h3>
<li>
	@foreach(var student in Model)
	{
		<div>
			<ul>
				<li>
					<div class="mb-3">FirstName:@student.FirstName<br></div>
					<div class="mb-3">LastName:@student.LastName<br></div>
					<div class="mb-3">Email:@student.Email</div>
				</li>
			</ul>
		</div>
	}
</li>

MVCPractice/Views/Student/Login.cshtml
@model MVCPractice.Models.Student
<h2>Login your account here!</h2>

<div class="row">
	<div class="col-6">
		<div class="card">
			<div class="card-header">
				<h3>Login</h3>
			</div>

			<div class="card-body">
				<form asp-controller="Student" asp-action="LoginStudent" method="post">
					<div class="mb-3">
						<label class="form-label">FirstName</label>
						<input asp-for="FirstName" type="text" class="form-control" />
					</div>

					<div class="mb-3">
						<label class="form-label">Email</label>
						<input asp-for="Email" type="text" class="form-control" />
					</div>

					<div>
						<button type="submit" class="btn btn-secondary">Login</button>
					</div>
				</form>
			</div>

			<div class="card-footer"></div>
		</div>
	</div>
</div>

MVCPractice/Views/Student/Register.cshtml
@model MVCPractice.Models.Student
<h2>Register your account here!</h2>
<div class= "row">
	<div class="col-6">
		<div class="card">
			<div class="card-header">
				<h4>Register</h4>
			</div>

			<div class="card-body">
               <form asp-controller="Student" asp-action="RegisterStudent" method="post">
				   <div class="mb-3">
					   <label class="form-label">FirstName</label>
					   <input asp-for =FirstName type="text" class="form-control" />
				   </div>

				   <div class="mb-3">
					   <label class="form-label">LastName</label>
					   <input asp-for="LastName" type="text" class="form-control"/>
				   </div>

				   <div class="mb-3">
					   <label class="form-label">Email</label>
						<input asp-for="Email" type="email" class="form-control" />
				   </div>

				   <div>
					   <button type="submit" class="btn btn-success">Register</button>
				   </div>
			   </form>
			</div>

			<div class="card-footer"></div>
		</div>
	</div>
</div>