FileUpload/Models/DogViewModel.cs
namespace FileUpload.Models
{
	public class DogViewModel
	{
		public string Name { get; set; }
		public int Age { get; set; }

	}
}

FileUpload/Models/ErrorViewModel.cs
namespace FileUpload.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FileUpload/Controllers/HelloWorldController.cs
using FileUpload.Models;
using Microsoft.AspNetCore.Mvc;

namespace FileUpload.Controllers
{
	public class HelloWorldController : Controller
	{
		private static List<DogViewModel> doggos = new List<DogViewModel>();
		public IActionResult Index()
		{
			return View(doggos);
		}

		public IActionResult Create()
		{
			var createNewDog = new DogViewModel();
			return View(createNewDog);
		}

		public IActionResult CreateDog(DogViewModel model)
		{
			//return View("Index");
			doggos.Add(model);
			return RedirectToAction(nameof(Index));
		}

		public IActionResult Greeting()
		{
			DogViewModel doggos = new DogViewModel()
			{
				Name = "Petter",
				Age = 20,
			};
			return View(doggos);
		}
	}
}

FileUpload/Controllers/HomeController.cs
using System.Diagnostics;
using FileUpload.Models;
using Microsoft.AspNetCore.Mvc;

namespace FileUpload.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FileUpload/Views/HelloWorld/Create.cshtml
@model DogViewModel
<h1>Create</h1>
<hr />
<div class="row">
	<div class="col-6">

		<div class="card">
			<div class="card-header">
				<h5>Create new dog</h5>
			</div>

			<div class="card-body">
				<form asp-controller="HelloWorld" asp-action="CreateDog" method="post">
					
					<div class="mb-3">
						<label class="form-label">Dog Name</label>
						<input asp-for=Name type="text" class="form-control" />
					</div>

					<div class="mb-3">
						<label class="form-label">Dog Age</label>
						<input asp-for=Age type="number" class="form-control" />
					</div>

					<div class="mb-3">
						<button type = "submit" class="btn btn-primary">Save</button>
					</div>
				</form>
			</div>

			<div class="card-footer"></div>
		</div>
		
	</div>
</div>

FileUpload/Views/HelloWorld/Greeting.cshtml
@model FileUpload.Models.DogViewModel

<h1>The name of my dog is @Model.Name</h1>
<p>The age of my dog is @Model.Age</p>

FileUpload/Views/HelloWorld/Index.cshtml
@model List<FileUpload.Models.DogViewModel>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<ul>
    @foreach (var dog in Model)
    {
        <li>
            <ul>
                <li>
                    Name: @dog.Name
                </li>
                <li>Age: @dog.Age</li>
            </ul>
        </li>
    }
</ul>

FileUpload/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FileUpload/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FileUpload</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FileUpload.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="HelloWorld" asp-action="Greeting">Greet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HelloWorld" asp-action="Index">Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HelloWorld" asp-action="Create">Create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FileUpload - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>